### ISSUE TITLE
Wybór technologii

### ISSUE THREAD

**Issue by StanislawHorna** [PLProjektKompetencyjny/PK_6IO1z_Projekt4_Frontend#2]

**Comment by PrzemyslawKowalskiPK** [comment]
Rozważamy wybór pomiędzy **Angular** a **Svelte**

**Comment by abienias97** [comment]
Wybieramy Angulara

**Comment by PrzemyslawKowalskiPK** [comment]
Zdecydowaliśmy się na framework **Angular** ze względu na potencjał rozwijania aplikacji **Enterprise** oraz na lepszą znajomość tej technologii, która pojawiła się w trakcie toku studiów.
