### ISSUE TITLE
Stworzenie architektury frontendu

### ISSUE THREAD

**Issue by siemaEko** [PLProjektKompetencyjny/PK_6IO1z_Projekt4_Frontend#3]

**Comment by PrzemyslawKowalskiPK** [comment]
Jeśli chodzi o architekturę to sam Angular narzuca już pewien schemat tj. logiczny podział na;
- komponenty,
- moduły,
- serwisy,
- pipes,
- dyrektywy.

**Comment by abienias97** [comment]
Jeśli chodzi o komponenty to ja bym proponował na pewno komponent/moduł (tutaj zdaje się na wiedzę Przemka) od kalendarza oraz wirtualnego spaceru. Trzeba też jakoś logicznie rozdzielić Panel administracyjny od właściwej strony (tutaj też Przemo wkracza raczej bo nie wiem za bardzo jaki to poziom (komponent/moduł) w Angularze).

**Comment by PrzemyslawKowalskiPK** [comment]
Architektura jest opisana w pliku [README.md](https://github.com/PLProjektKompetencyjny/PK_6IO1z_Projekt4_Frontend/blob/develop/README.md#wytyczne) w projekcie `PK_6IO1z_Projekt4_Frontend` w sekcji `Wytyczne`.
