### ISSUE TITLE
Przygotowanie szablonu

### ISSUE THREAD

**Issue by PrzemyslawKowalskiPK** [PLProjektKompetencyjny/PK_6IO1z_Projekt4_Frontend#9]
https://dribbble.com/search/hotel

**Comment by abienias97** [comment]
https://www.templatemonster.com

**Comment by GringoXY** [comment]
> https://www.templatemonster.com

https://www.templatemonster.com/website-templates/luxury-hotel-amp-luxury-hotel-booking-html5-template-310619.html

**Comment by GringoXY** [comment]
https://www.free-css.com/template-categories/hotels

**Comment by StanislawHornaGitHub** [comment]
https://www.free-css.com/free-css-templates/page289/hotelier

**Comment by GringoXY** [comment]
Decydujemy się na: https://www.free-css.com/free-css-templates/page289/hotelier
